asf_contact_backend_homepage:
    path: /admin/contact
    defaults: { _controller: "ASFContactBundle:Default:index" }
    
asf_contact_identity:
    prefix: /admin/contact/identity
    resource: "@ASFContactBundle/Resources/config/routing/identity.yml"
    
asf_contact_doc:
    prefix: /admin/contact/doc
    resource: "@ASFContactBundle/Resources/config/routing/doc.yml"
    
